/**
 * Centralized error code registry.
 * Shared between server and frontend via @ouitransfer/shared/error-codes.
 *
 * Convention: SCREAMING_SNAKE_CASE, value === key.
 * Add new codes here — never use ad-hoc string literals.
 */
export const ErrorCodes = {
  // Auth
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // Resources
  NOT_FOUND: "NOT_FOUND",
  RECORD_NOT_FOUND: "RECORD_NOT_FOUND",
  CONFLICT: "CONFLICT",
  GONE: "GONE",

  // Database
  UNIQUE_CONSTRAINT: "UNIQUE_CONSTRAINT",
  FOREIGN_KEY_CONSTRAINT: "FOREIGN_KEY_CONSTRAINT",
  RELATION_VIOLATION: "RELATION_VIOLATION",
  DATABASE_ERROR: "DATABASE_ERROR",

  // Storage
  STORAGE_UNREACHABLE: "STORAGE_UNREACHABLE",
  DISK_SPACE_DETECTION_FAILED: "DISK_SPACE_DETECTION_FAILED",
  DISK_SPACE_ERROR: "DISK_SPACE_ERROR",
  FILE_SIZE_EXCEEDED: "FILE_SIZE_EXCEEDED",
  INSUFFICIENT_STORAGE: "INSUFFICIENT_STORAGE",

  // System
  INTERNAL_ERROR: "INTERNAL_ERROR",
  RESPONSE_SERIALIZATION_ERROR: "RESPONSE_SERIALIZATION_ERROR",
  FASTIFY_ERROR: "FASTIFY_ERROR",
  COPY_FAILED: "COPY_FAILED",

  // Shares
  PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  SHARE_EXPIRED: "SHARE_EXPIRED",
  MAX_VIEWS_REACHED: "MAX_VIEWS_REACHED",
  SHARE_INACTIVE: "SHARE_INACTIVE",

  // Upload
  UPLOAD_FAILED: "UPLOAD_FAILED",

  // LDAP
  LDAP_SYNC_IN_PROGRESS: "LDAP_SYNC_IN_PROGRESS",
  LDAP_CONFIG_NOT_FOUND: "LDAP_CONFIG_NOT_FOUND",
  LDAP_CONNECTION_FAILED: "LDAP_CONNECTION_FAILED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
